[package]
name = "rui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rui"


[dependencies]
glow = "0.13.1"
sdl2 = "0.36.0"
swash = "0.1.13"
